export const MOTIVATIONAL_QUOTES = [
  "You don't have to act on every thought. This one can pass.",
  "The cigarette won't solve what you're feeling — but this breath might.",
  "Your body is learning freedom. Let it.",
  "Say no to this urge, say yes to the life you're building.",
  "The urge is loud now, but it won't last.",
  "Not today. Not anymore.",
  "You are not the craving. You are the awareness behind it.",
  "Every time you pause, you prove you're in control.",
  "You're practicing peace — one urge at a time.",
  "This is healing. This is hard. You're doing both.",
  "That cigarette is a step backward. You're walking forward now.",
  "The smoke fades fast. Your progress doesn't.",
  "Every 'no' is a victory your old self never thought possible.",
  "You're not alone. Millions have made it through this moment.",
  "This is a test. And you're passing it.",
  "You won't always feel like this. But you'll always be proud you resisted.",
  "Relief is not in the cigarette — it's in your choice not to light it.",
  "What you want most is stronger than what you want now.",
  "Feel it, name it, breathe through it — and let it go.",
  "One more urge passed. One less chain holding you.",
  "This is the new you — the one who doesn't give in.",
  "You've quit before — now you're choosing to stay free.",
  "The urge is just a signal. You don't have to follow it.",
  "This is your moment of power. Choose wisely.",
  "You don't need to fight it. You just need to wait it out.",
  "The craving is temporary, but the freedom is permanent.",
  "You are stronger than this moment. Breathe through it.",
  "This feeling will pass. Your strength will not.",
  "Every craving you overcome is a battle you've won.",
  "Your future self is thanking you right now.",
  "Observe the feeling without judgment. Let it float by.",
  "This urge is not a command. Let it come. Let it go.",
  "You don't need a cigarette — you need a deep breath and a little time.",
  "Progress is made one decision at a time. You just made one.",
  "Cravings lie. You already know the truth.",
  "You've come too far to light that up.",
  "Each time you say no, you say yes to your health.",
  "Discomfort is part of change. You're doing it.",
  "You've felt this before. And you made it through.",
  "What you're building today is freedom for life.",
  "You're not quitting smoking — you're reclaiming control.",
  "It's okay to feel the urge. It's not okay to let it lead.",
  "You're teaching your body a new truth: you don't need this.",
  "This is your brain rewiring. Let it work.",
  "The urge will fade. Your progress will not.",
  "You've handled harder things than this. This is just a moment.",
  "No puff is worth your peace.",
  "Feel the discomfort. Stay with it. That's growth.",
  "Cravings are signs of healing. You're getting better.",
  "Remember why you started — and keep going.",
  "Let the craving pass. Don't give it power.",
  "Your lungs are already thanking you.",
  "Each urge resisted builds your freedom muscle.",
  "Freedom is built one no at a time.",
  "The only way out is through. You're doing it."
];